// ─── CrisisMonitor ────────────────────────────────────────────────────────────
//
// Three-level crisis detection system:
//
//   Level 1 — Mild distress: no intervention, normal flow
//   Level 2 — Concerning ideation: soft prompt injection, LLM still called
//   Level 3 — Explicit self-harm intent: bypass LLM entirely, return
//              structured human-authored crisis response immediately
//
// Detection is based on weighted phrase matching with negation detection.
// Generic words like "help", "stress", "sad" are explicitly excluded.
//
// ─────────────────────────────────────────────────────────────────────────────

export type CrisisLevel = 1 | 2 | 3;

export interface CrisisAssessment {
    /** 1 = safe/mild, 2 = concerning ideation, 3 = explicit self-harm intent */
    level: CrisisLevel;
    /** Only populated for Level 3 — bypasses LLM entirely */
    structuredResponse?: string;
    /** Only populated for Level 2 — injected into PromptConstructor */
    promptInjection?: string;
    /** Which phrases matched */
    matchedPhrases: string[];
}

// ─── Phrase Banks ─────────────────────────────────────────────────────────────

/**
 * Level 3 — Explicit, direct self-harm / suicidal intent.
 * All require first-person framing to avoid false positives.
 */
const LEVEL_3_PATTERNS: { id: string; re: RegExp }[] = [
    { id: 'want_to_kill_myself', re: /\bi\s*(?:really\s*)?(?:want|wanna)\s*to\s*kill\s*myself\b/i },
    { id: 'going_to_kill_myself', re: /\bi\s*(?:'?m|am)\s*(?:going|planning|plan)\s*to\s*kill\s*myself\b/i },
    { id: 'want_to_die', re: /\bi\s*(?:really\s*)?(?:want|wanna)\s*to\s*die\b/i },
    { id: 'want_to_hurt_myself', re: /\bi\s*(?:want|wanna)\s*to\s*hurt\s*myself\b/i },
    { id: 'dont_want_to_live', re: /\bi\s*(?:don'?t|do not)\s*want\s*to\s*live\s*(?:anymore|any more)?\b/i },
    { id: 'going_to_end_it', re: /\bi'?m?\s*(?:going|planning)\s*to\s*end\s*it\b/i },
    { id: 'end_my_life', re: /\b(?:want|wanna|going|plan)\s*to\s*end\s*my\s*life\b/i },
    { id: 'take_my_own_life', re: /\b(?:want|wanna|going|plan)\s*to\s*take\s*my\s*own\s*life\b/i },
    { id: 'no_reason_to_live', re: /\bthere\s*(?:is|'s)\s*no\s*reason\s*to\s*live\b/i },
    { id: 'better_off_dead', re: /\bi'?d?\s*be\s*better\s*(?:off\s*dead|off\s*gone)\b/i },
];

/**
 * Level 2 — Concerning ideation, moderate risk.
 * Does not bypass LLM — instead injects heightened empathy instruction.
 */
const LEVEL_2_PATTERNS: { id: string; re: RegExp }[] = [
    { id: 'feel_suicidal', re: /\bi\s*(?:feel|am|'?m)\s*suicidal\b/i },
    { id: 'think_about_hurting', re: /\bi\s*(?:think|thought)\s*about\s*hurting\s*myself\b/i },
    { id: 'cant_go_on', re: /\bi\s*(?:can'?t|cannot)\s*go\s*on\b/i },
    { id: 'thinking_about_suicide', re: /\bi(?:'?m)?\s*(?:thinking|thought)\s*about\s*suicide\b/i },
    { id: 'having_suicidal_thoughts', re: /\bi\s*(?:'?m|am)\s*having\s*suicidal\s*thoughts?\b/i },
    { id: 'no_point', re: /\bthere'?s?\s*(?:is\s*)?no\s*point\s*(?:to|in)\s*(?:this|life|anything|living)\b/i },
];

/** Explicit non-crisis words — never escalate on these alone */
const SAFE_SINGLE_WORDS = new Set(['help', 'stress', 'sad', 'tired', 'upset', 'frustrated']);

// ─── Helpers ──────────────────────────────────────────────────────────────────

function normalize(input: string): string {
    return input
        .toLowerCase()
        .replace(/['']/g, "'")
        .replace(/\s+/g, ' ')
        .trim();
}

function isNegated(msg: string, matchIndex: number): boolean {
    const windowStart = Math.max(0, matchIndex - 24);
    const prefix = msg.slice(windowStart, matchIndex);
    return /\b(don'?t|dont|do not|not|never|no)\b/i.test(prefix);
}

function matchPhrases(
    msg: string,
    patterns: { id: string; re: RegExp }[]
): string[] {
    const matched: string[] = [];
    for (const p of patterns) {
        const m = msg.match(p.re);
        if (!m || m.index == null) continue;
        if (isNegated(msg, m.index)) continue;
        matched.push(p.id);
    }
    return matched;
}

// ─── Structured Crisis Response (Level 3) ────────────────────────────────────
//
// Human-authored — never generated by the model.
// Calm, direct, non-clinical, non-robotic.
//

const LEVEL_3_RESPONSES: string[] = [
    "What you're feeling right now is real, and you don't have to face it alone. Please reach out to someone you trust right now — a friend, family member, or anyone nearby. You can also call iCall at 9152987821 or the Vandrevala Foundation helpline at 1860-2662-345, both available across India.",

    "I hear you, and I'm glad you said something. This is a moment where real human support matters most. Please talk to someone close to you, or reach out to a crisis line — iCall at 9152987821 or AASRA at 9820466627 are available to help you right now.",

    "You matter, and what you're going through deserves real support. Please don't carry this alone — speak to someone you trust, or call iCall at 9152987821 (Monday–Saturday, 8am–10pm) or the Vandrevala Foundation at 1860-2662-345, available 24 hours.",
];

const LEVEL_2_PROMPT_INJECTION =
    'User shows concerning emotional distress. Respond with heightened empathy and gently encourage seeking support. Do not minimize their experience. Express care clearly.';

// ─── CrisisMonitor ────────────────────────────────────────────────────────────

export class CrisisMonitor {
    /**
     * Assesses a message for crisis signals.
     * Returns a CrisisAssessment with level, optional LLM bypass response,
     * and optional prompt injection for Level 2.
     */
    static assess(message: string): CrisisAssessment {
        const msg = normalize(message);

        // Explicit safe single-word guard
        if (SAFE_SINGLE_WORDS.has(msg)) {
            return { level: 1, matchedPhrases: [] };
        }

        // ── Level 3 check first (highest priority) ────────────────────────────
        const level3Matches = matchPhrases(msg, LEVEL_3_PATTERNS);
        if (level3Matches.length > 0) {
            const responseIndex = Math.floor(Math.random() * LEVEL_3_RESPONSES.length);
            return {
                level: 3,
                structuredResponse: LEVEL_3_RESPONSES[responseIndex],
                matchedPhrases: level3Matches,
            };
        }

        // ── Level 2 check ─────────────────────────────────────────────────────
        const level2Matches = matchPhrases(msg, LEVEL_2_PATTERNS);
        if (level2Matches.length > 0) {
            return {
                level: 2,
                promptInjection: LEVEL_2_PROMPT_INJECTION,
                matchedPhrases: level2Matches,
            };
        }

        // ── Level 1 — normal flow ─────────────────────────────────────────────
        return { level: 1, matchedPhrases: [] };
    }
}
