import { ScrollText, AlertTriangle, HeartHandshake, Ban, RefreshCw, Mail } from 'lucide-react';
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';
import { AnimatedBackground } from '../components/AnimatedBackground';

export const metadata = {
    title: 'Terms of Use | Solitude',
    description: 'Terms of Use for Solitude — a mental wellbeing conversational companion.',
};

const sections = [
    {
        icon: HeartHandshake,
        title: 'Nature of the Service',
        body: `Solitude is a conversational companion designed to support emotional wellbeing. It is not a licensed therapeutic service, medical provider, or crisis intervention platform. The responses generated by Solitude are AI-assisted and are intended for general emotional support only — they should not be treated as professional mental health advice, diagnosis, or treatment.`,
    },
    {
        icon: AlertTriangle,
        title: 'Not a Substitute for Professional Help',
        body: `If you are experiencing a mental health crisis, thoughts of self-harm, or any medical emergency, please contact a qualified professional or a crisis helpline immediately. In India, you can reach iCall at 9152987821 (Monday–Saturday, 8 am–10 pm). Solitude is a supplement to — not a replacement for — professional mental health support.`,
    },
    {
        icon: ScrollText,
        title: 'Acceptable Use',
        body: `By using Solitude you agree to engage with the platform in good faith and for its intended purpose — personal emotional wellbeing and reflection. You agree not to use Solitude to share harmful content, attempt to extract sensitive data, reverse-engineer the system, or misrepresent the nature of the service to others.`,
    },
    {
        icon: Ban,
        title: 'Limitations of Liability',
        body: `Solitude is provided "as is" without warranties of any kind. We make no guarantee regarding the accuracy, completeness, or appropriateness of any AI-generated response. To the fullest extent permitted by law, Solitude and its developers shall not be liable for any outcome arising from reliance on the service.`,
    },
    {
        icon: RefreshCw,
        title: 'Changes to These Terms',
        body: `We may update these Terms of Use from time to time to reflect changes in the service or applicable regulations. Continued use of Solitude after any update constitutes acceptance of the revised terms. We encourage you to review this page periodically.`,
    },
    {
        icon: Mail,
        title: 'Contact',
        body: `If you have questions about these terms or how the service works, you are welcome to reach out via the Contact page. We are a small team building Solitude with care, and we take your concerns seriously.`,
    },
];

export default function TermsPage() {
    return (
        <div className="min-h-screen flex flex-col pt-32 relative">
            <AnimatedBackground />
            <Navbar />

            <main className="flex-grow max-w-4xl mx-auto px-6 py-20 w-full relative z-10">
                {/* Header */}
                <div className="text-center space-y-4 mb-20">
                    <h1 className="text-5xl md:text-6xl text-white serif italic">Terms of Use</h1>
                    <p className="text-xl text-slate-300">Please read these terms before using Solitude.</p>
                    <p className="text-sm text-slate-500 uppercase tracking-widest font-semibold">
                        Effective: March 2026
                    </p>
                </div>

                {/* Intro card */}
                <div className="bg-sol-teal/5 border border-sol-teal/15 rounded-[2rem] px-10 py-8 mb-12 text-slate-300 leading-relaxed text-base">
                    Solitude exists to offer a calm, private space for emotional reflection. These terms clarify
                    what the service is, what it is not, and how we expect it to be used. By accessing or using
                    Solitude you agree to these terms.
                </div>

                {/* Sections */}
                <div className="bg-sol-glass backdrop-blur-xl border border-white/10 p-12 md:p-16 rounded-[3rem] shadow-2xl space-y-14">
                    {sections.map((section, i) => {
                        const Icon = section.icon;
                        return (
                            <div key={i} className={`flex flex-col md:flex-row gap-8 items-start ${i > 0 ? 'pt-12 border-t border-white/5' : ''}`}>
                                <div className="w-14 h-14 bg-sol-teal/10 rounded-2xl flex items-center justify-center text-sol-teal shrink-0">
                                    <Icon size={26} />
                                </div>
                                <div className="space-y-3">
                                    <h2 className="text-2xl font-heading font-bold text-white">
                                        {i + 1}. {section.title}
                                    </h2>
                                    <p className="text-slate-300 leading-relaxed text-lg font-light">
                                        {section.body}
                                    </p>
                                </div>
                            </div>
                        );
                    })}
                </div>

                {/* Footer note */}
                <p className="text-center text-slate-500 text-sm mt-16 leading-relaxed">
                    These Terms of Use govern your use of the Solitude conversational companion service.
                    They do not constitute a legal contract between you and any licensed mental health provider.
                </p>
            </main>

            <Footer />
        </div>
    );
}
